version: "3"
services:
  node:
    build:
      context: ./config/node/
      args:
        NODE_IMAGES: ${NODE_IMAGES}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
    networks:
      - default

  go:
    build:
      context: ./config/golang/
      args:
        GO_IMAGES: ${GO_IMAGES}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
    networks:
      - default

  nginx:
    build:
      context: ./config/nginx/
      args:
        NGINX_IMAGES: ${NGINX_IMAGES}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${LETSENCRYPT_DATA_DIR}:/etc/nginx/letsencrypt/:rw
    restart: always
    networks:
      - default

  php72:
    build:
      context: ./config/php/
      args:
        PHP_VERSION: ${PHP72_VERSION}
        PHP_IMAGES: ${PHP72_IMAGES}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP72_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php72.sh
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP72_LOG_DIR}:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    build:
      context: ./config/mysql/
      args:
        MYSQL_IMAGES: ${MYSQL_IMAGES}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    build:
      context: ./config/redis/
      args:
        REDIS_IMAGES: ${REDIS_IMAGES}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default

  mongodb:
    build:
      context: ./config/mongodb/
      args:
        MONGODB_IMAGES: ${MONGODB_IMAGES}
    environment:
        MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
        MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
    volumes:
      - ${MONGODB_DATA_DIR}:/data/db:rw
      - ${MONGODB_DATA_DIR}/mongo_key:/mongo:rw
    ports:
       - "${MONGODB_HOST_PORT}:27017"
    networks:
       - default
    command:
       --auth


